#theme: minima
title: civirat034
#description: 
author: civirat034
#email: 

# 其他常用配置
remote_theme: pages-themes/leap-day@v0.2.0
markdown: kramdown
highlighter: rouge
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
- jekyll-feed
